@startuml
[*] --> ACCEPT_DATA_IN : RESET

ACCEPT_DATA_IN : TVALID_OUT=0
ACCEPT_DATA_IN : TREADY_IN=1
ACCEPT_DATA_IN : COUNTER=0
ACCEPT_DATA_IN : TLAST=0
'----------------------------------------------
ACCEPT_DATA_IN --> ACCEPT_DATA_IN : TVALID_IN=0
ACCEPT_DATA_IN --> DATA_OUT       : TVALID_IN=1


DATA_OUT : TVALID_OUT=1
DATA_OUT : TREADY_IN=0
DATA_OUT : if(TREADY_OUT): COUNTER+=1 else COUNTER=COUNTER
DATA_OUT : TLAST=0
'---------------------------------------------
DATA_OUT --> DATA_OUT      : (TREADY_OUT=0) OR \n (TREADY_OUT=1 && LAST_SUBTRANSFER=0)
DATA_OUT --> LAST_DATA_OUT : TREADY_OUT=1 \n LAST_SUBTRANSFER=1



LAST_DATA_OUT : TVALID_OUT=1
LAST_DATA_OUT : TREADY_IN=1
LAST_DATA_OUT : COUNTER=0
LAST_DATA_OUT : TLAST=TLAST_RECEIVED
'---------------------------------------------
LAST_DATA_OUT --> LAST_DATA_OUT  : TREADY_OUT=0
LAST_DATA_OUT --> ACCEPT_DATA_IN : TREADY_OUT=1 \n TVALID_IN=0
LAST_DATA_OUT --> DATA_OUT       : TREADY_OUT=1 \n TVALID_IN=1

@enduml