@startuml
[*] --> ACCEPT_DATA_IN : RESET

ACCEPT_DATA_IN : TVALID_OUT=0
ACCEPT_DATA_IN : TREADY_IN=1
ACCEPT_DATA_IN : if TVALID_IN then COUNTER+=1 else COUNTER=COUNTER
'----------------------------------------------
ACCEPT_DATA_IN --> ACCEPT_DATA_IN : LAST_SUBTRANSFER=0 \n TLAST_IN=0
ACCEPT_DATA_IN --> DATA_OUT       : LAST_SUBTRANSFER=1
ACCEPT_DATA_IN --> PAD : LAST_SUBTRANSFER=0 \n TLAST_IN=1


PAD : TVALID_OUT=0
PAD : TREADY_IN=0
PAD : COUNTER+=1
'---------------------------------------------
PAD --> PAD      : LAST_SUBTRANSFER=0
PAD --> DATA_OUT : LAST_SUBTRANSFER=1


DATA_OUT : TVALID_OUT=1
DATA_OUT : TREADY_OUT=TREADY_IN
DATA_OUT : if(TREADY_OUT): COUNTER=1 else COUNTER=0
'---------------------------------------------
DATA_OUT --> DATA_OUT       : TREADY_OUT=0
DATA_OUT --> ACCEPT_DATA_IN : TREADY_OUT=1

@enduml
