@startuml
[*] --> NO_VALID_DATA_IN : RESET

NO_VALID_DATA_IN : TVALID_OUT=TVALID_IN
NO_VALID_DATA_IN : TREADY_IN=TREADY_OUT
NO_VALID_DATA_IN : COUNTER=0
'----------------------------------------------
NO_VALID_DATA_IN --> NO_VALID_DATA_IN :           TVALID_IN=0 \n TREADY_OUT=X \n COUNTER=X
NO_VALID_DATA_IN --> VALID_DATA_IN_NO_READY_OUT : TVALID_IN=1 \n TREADY_OUT=0 \n COUNTER=X
NO_VALID_DATA_IN --> ACCEPT_DATA_IN :             TVALID_IN=1 \n TREADY_OUT=1 \n COUNTER=X


VALID_DATA_IN_NO_READY_OUT : TVALID_OUT=TVALID_IN
VALID_DATA_IN_NO_READY_OUT : TREADY_IN=TREADY_OUT
VALID_DATA_IN_NO_READY_OUT : COUNTER=0
'----------------------------------------------
VALID_DATA_IN_NO_READY_OUT --> VALID_DATA_IN_NO_READY_OUT : TVALID_IN=1 \n TREADY_OUT=0 \n COUNTER=X
VALID_DATA_IN_NO_READY_OUT --> ACCEPT_DATA_IN :             TVALID_IN=1 \n TREADY_OUT=1 \n COUNTER=X
VALID_DATA_IN_NO_READY_OUT --> NO_VALID_DATA_IN :           TVALID_IN=0 \n TREADY_OUT=X \n COUNTER=X


ACCEPT_DATA_IN : TVALID_OUT=1
ACCEPT_DATA_IN : TREADY_OUT=1
ACCEPT_DATA_IN : COUNTER=0
'---------------------------------------------
ACCEPT_DATA_IN --> DATA_OUT :                   TVALID_IN=X \n TREADY_OUT=1 \n COUNTER=X
ACCEPT_DATA_IN --> NO_READY_IN_TRANSMISSION :   TVALID_IN=X \n TREADY_OUT=0 \n COUNTER=X


NO_READY_IN_TRANSMISSION : TVALID_OUT=1
NO_READY_IN_TRANSMISSION : TREADY_OUT=0
NO_READY_IN_TRANSMISSION : COUNTER=COUNTER
'---------------------------------------------
NO_READY_IN_TRANSMISSION --> NO_READY_IN_TRANSMISSION : TVALID_IN=X \n TREADY_OUT=0 \n COUNTER=X
NO_READY_IN_TRANSMISSION --> DATA_OUT :                 TVALID_IN=X \n TREADY_OUT=1 \n COUNTER=X


DATA_OUT : TVALID_OUT=1
DATA_OUT : TREADY_OUT=0
DATA_OUT : COUNTER+=1
'---------------------------------------------
DATA_OUT --> DATA_OUT :                   TVALID_IN=X \n TREADY_OUT=1 \n COUNTER≠MAX_SUB_TRANSFER_INDEX
DATA_OUT --> NO_READY_IN_TRANSMISSION :   TVALID_IN=X \n TREADY_OUT=0 \n COUNTER≠MAX_SUB_TRANSFER_INDEX
DATA_OUT --> ACCEPT_DATA_IN :             TVALID_IN=1 \n TREADY_OUT=1 \n COUNTER=MAX_SUB_TRANSFER_INDEX
DATA_OUT --> VALID_DATA_IN_NO_READY_OUT : TVALID_IN=1 \n TREADY_OUT=0 \n COUNTER=MAX_SUB_TRANSFER_INDEX
DATA_OUT --> NO_VALID_DATA_IN :           TVALID_IN=0 \n TREADY_OUT=X \n COUNTER=MAX_SUB_TRANSFER_INDEX

@enduml
